/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';


import {
  MyOwnHn as MyOwnHn
} from './components/my-own-hn/my-own-hn';

declare global {
  interface HTMLMyOwnHnElement extends MyOwnHn, HTMLElement {
  }
  var HTMLMyOwnHnElement: {
    prototype: HTMLMyOwnHnElement;
    new (): HTMLMyOwnHnElement;
  };
  interface HTMLElementTagNameMap {
    "my-own-hn": HTMLMyOwnHnElement;
  }
  interface ElementTagNameMap {
    "my-own-hn": HTMLMyOwnHnElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-own-hn": JSXElements.MyOwnHnAttributes;
    }
  }
  namespace JSXElements {
    export interface MyOwnHnAttributes extends HTMLAttributes {
      
    }
  }
}

