/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import {
  RouterHistory,
} from '@stencil/router';

import {
  MyOwnHn as MyOwnHn
} from './components/my-own-hn/my-own-hn';

declare global {
  interface HTMLMyOwnHnElement extends MyOwnHn, HTMLElement {
  }
  var HTMLMyOwnHnElement: {
    prototype: HTMLMyOwnHnElement;
    new (): HTMLMyOwnHnElement;
  };
  interface HTMLElementTagNameMap {
    "my-own-hn": HTMLMyOwnHnElement;
  }
  interface ElementTagNameMap {
    "my-own-hn": HTMLMyOwnHnElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-own-hn": JSXElements.MyOwnHnAttributes;
    }
  }
  namespace JSXElements {
    export interface MyOwnHnAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  NewsPage as NewsPage
} from './components/news-page/news-page';

declare global {
  interface HTMLNewsPageElement extends NewsPage, HTMLElement {
  }
  var HTMLNewsPageElement: {
    prototype: HTMLNewsPageElement;
    new (): HTMLNewsPageElement;
  };
  interface HTMLElementTagNameMap {
    "news-page": HTMLNewsPageElement;
  }
  interface ElementTagNameMap {
    "news-page": HTMLNewsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "news-page": JSXElements.NewsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface NewsPageAttributes extends HTMLAttributes {
      
        match?: any,
        history?: RouterHistory
    }
  }
}


import {
  StoryList as StoryList
} from './components/story-list/story-list';

declare global {
  interface HTMLStoryListElement extends StoryList, HTMLElement {
  }
  var HTMLStoryListElement: {
    prototype: HTMLStoryListElement;
    new (): HTMLStoryListElement;
  };
  interface HTMLElementTagNameMap {
    "story-list": HTMLStoryListElement;
  }
  interface ElementTagNameMap {
    "story-list": HTMLStoryListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "story-list": JSXElements.StoryListAttributes;
    }
  }
  namespace JSXElements {
    export interface StoryListAttributes extends HTMLAttributes {
      
        stories?: any
    }
  }
}

